INTERFACE zfi_if_fidoc_types PUBLIC.

  "============================================================
  " 1. KIỂU DỮ LIỆU GIẢI MÃ JSON (JSON DESERIALIZATION TYPES)
  "============================================================
  TYPES: BEGIN OF ts_doc_item_request,
           idline                  TYPE string,
           accountingdocumentitem  TYPE string,
           postingkey              TYPE string,
           account                 TYPE string,
           mainassetnumber         TYPE string,
           subassetnumber          TYPE string,
           specialglaccount        TYPE string,
           assettransactiontype    TYPE string,
           companycodecurrency     TYPE string,
           amountinlocalcurrency   TYPE string,
           transactioncurrency     TYPE string,
           amountindoumentcurrency TYPE string,
           exchangerate            TYPE string,
           taxbaseamount           TYPE string,
           localtaxbaseamount      TYPE string,
           assignment              TYPE string,
           businessarea            TYPE string,
           costcenter              TYPE string,
           profitcenter            TYPE string,
           internalorder           TYPE string,
           assetvaluedate          TYPE string,
           itemtext                TYPE string,
           overrideglaccount       TYPE string,
           taxcode                 TYPE string,
           segment                 TYPE string,
           paymentterms            TYPE string,
           paymentblockreason      TYPE string,
           paymentmethod           TYPE string,
           contractnumber          TYPE string,
           contracttype            TYPE string,
           housebank               TYPE string,
           bankaccountid           TYPE string,
           invoicerefnum           TYPE string,
           invoicereffiscalyear    TYPE string,
           invoicereflineitem      TYPE string,
           purchasingno            TYPE string,
           purchasingitem          TYPE string,
           baselinedate            TYPE string,
           valuedate               TYPE string,
           saleorder               TYPE string,
           saleorderitem           TYPE string,
           ref_1                   TYPE string,
           ref_2                   TYPE string,
           ref_3                   TYPE string,
           longtext                TYPE string,
           unit                    TYPE string,
           name_1                  TYPE string,
           name_2                  TYPE string,
           name_3                  TYPE string,
           name_4                  TYPE string,
           taxnumber_1             TYPE string,
           city                    TYPE string,
           country                 TYPE string,
           vatregno                TYPE string,
           quantity                TYPE string,
           customer                TYPE string,
           supplier                TYPE string,
           alternativepayee        TYPE string,
           mst                     TYPE string,
           tennccxuathd            TYPE string,
           mstnccxuathd            TYPE string,
           netduedate              TYPE string,
           namecus_1               TYPE string,
           namecus_2               TYPE string,
           namecus_3               TYPE string,
           namecus_4               TYPE string,
           citycus                 TYPE string,
           countrycus              TYPE string,
           mstcus                  TYPE string,
           cusgroup                TYPE string,
           division                TYPE string,
           distributionchannel     TYPE string,
           salesoffice             TYPE string,
           salesemployee           TYPE string,
           salesgroup              TYPE string,
           materialgroup           TYPE string,
           product                 TYPE string,
           wbselement              TYPE string,
           plant                   TYPE string,
           salesorganization       TYPE string,
           countrygl               TYPE string,
           namemotzeiv             TYPE string,
           cityzeiv                TYPE string,
           baseunit                TYPE string,
           orderid                 TYPE string,
           material                TYPE string,
           negativeposting         TYPE string,
         END OF ts_doc_item_request.

  TYPES: BEGIN OF ts_doc_request,
           id_doc       TYPE string,
           companycode  TYPE string,
           documentdate TYPE string,
           postingdate  TYPE string,
           documenttype TYPE string,
           currency     TYPE string,
           headertext   TYPE string,
           referencedoc TYPE string,
           headerref1   TYPE string,
           to_item      TYPE STANDARD TABLE OF ts_doc_item_request WITH EMPTY KEY,
         END OF ts_doc_request.

  TYPES: BEGIN OF ts_post_request,
           isupdate TYPE string,
           testmode TYPE string,
           filename TYPE string,
           doc      TYPE STANDARD TABLE OF ts_doc_request WITH EMPTY KEY,
         END OF ts_post_request.

  "============================================================
  " 2. KIỂU DỮ LIỆU XỬ LÝ NỘI BỘ (INTERNAL PROCESSING TYPES)
  "============================================================
  TYPES: BEGIN OF ts_item,
           idline                  TYPE zfi_de_id_line,
           accountingdocumentitem  TYPE buzei,
           postingkey              TYPE bschl,
           account                 TYPE hkont,
           mainassetnumber         TYPE zfi_de_anln1,
           subassetnumber          TYPE zfi_de_anln2,
           specialglaccount        TYPE i_specialglcode-specialglcode,
           assettransactiontype    TYPE i_assettransactiontype-assettransactiontype,
           companycodecurrency     TYPE waers,
           amountinlocalcurrency   TYPE fins_vwcur12,
           transactioncurrency     TYPE waers,
           amountindoumentcurrency TYPE fins_vwcur12,
           exchangerate            TYPE zfi_de_kursf,
           taxbaseamount           TYPE fins_vwcur12,
           localtaxbaseamount      TYPE fins_vwcur12,
           assignment              TYPE dzuonr,
           businessarea            TYPE gsber,
           costcenter              TYPE kostl,
           profitcenter            TYPE prctr,
           internalorder           TYPE aufnr,
           assetvaluedate          TYPE dats,
           itemtext                TYPE sgtxt,
           overrideglaccount       TYPE hkont,
           taxcode                 TYPE bukrs,
           segment                 TYPE i_segment-segment,
           paymentterms            TYPE dzterm,
           paymentblockreason      TYPE c LENGTH 1,
           paymentmethod           TYPE c LENGTH 1,
           contractnumber          TYPE c LENGTH 13,
           contracttype            TYPE c LENGTH 1,
           housebank               TYPE hbkid,
           bankaccountid           TYPE hktid,
           invoicerefnum           TYPE c LENGTH 10,
           invoicereffiscalyear    TYPE gjahr,
           invoicereflineitem      TYPE n LENGTH 3,
           purchasingno            TYPE ebeln,
           purchasingitem          TYPE ebelp,
           baselinedate            TYPE dats,
           valuedate               TYPE dats,
           saleorder               TYPE vbeln_vl,
           saleorderitem           TYPE i_salesdocumentitem-salesdocumentitem,
           ref1                    TYPE c LENGTH 20,
           ref2                    TYPE c LENGTH 20,
           ref3                    TYPE c LENGTH 20,
           longtext                TYPE c LENGTH 100,
           unit                    TYPE meins,
           name1                   TYPE c LENGTH 40,
           name2                   TYPE c LENGTH 40,
           name3                   TYPE i_onetimeaccountsupplier-businesspartnername3,
           name4                   TYPE i_onetimeaccountsupplier-businesspartnername4,
           mst                     TYPE stcd1,
           city                    TYPE c LENGTH 40,
           country                 TYPE c LENGTH 3,
           namecus1                TYPE c LENGTH 40,
           namecus2                TYPE c LENGTH 40,
           namecus3                TYPE i_onetimeaccountsupplier-businesspartnername3,
           namecus4                TYPE i_onetimeaccountsupplier-businesspartnername4,
           mstcus                  TYPE i_onetimeaccountsupplier-taxid1,
           citycus                 TYPE c LENGTH 40,
           countrycus              TYPE c LENGTH 3,
           taxnumber1              TYPE i_onetimeaccountsupplier-taxid1,
           vatregno                TYPE stceg,
           quantity                TYPE menge_d,
           customer                TYPE i_customer-customer,
           supplier                TYPE lifnr,
           alternativepayee        TYPE lifnr,
           mstnccxuathd            TYPE c LENGTH 40,
           tennccxuathd            TYPE c LENGTH 80,
           netduedate              TYPE dats,
           cusgroup                TYPE i_glaccountlineitemrawdata-customergroup,
           division                TYPE spart,
           distributionchannel     TYPE vtweg,
           materialgroup           TYPE i_glaccountlineitemrawdata-soldproductgroup,
           product                 TYPE i_glaccountlineitemrawdata-soldproduct,
           wbselement              TYPE i_glaccountlineitemrawdata-wbselement,
           plant                   TYPE werks_d,
           salesorganization       TYPE ekorg,
           countrygl               TYPE i_glaccountlineitemrawdata-customersuppliercountry,
           namemotzeiv             TYPE c LENGTH 40,
           cityzeiv                TYPE c LENGTH 40,
           baseunit                TYPE i_glaccountlineitemrawdata-baseunit,
           orderid                 TYPE i_glaccountlineitemrawdata-orderid,
           material                TYPE i_glaccountlineitemrawdata-soldproduct,
           negativeposting         TYPE c LENGTH 1,
         END OF ts_item.

  TYPES: BEGIN OF ts_data,
           filename     TYPE zfi_de_filename,
           id_doc       TYPE zfi_de_id_doc,
           companycode  TYPE bukrs,
           documentdate TYPE dats,
           postingdate  TYPE dats,
           documenttype TYPE blart,
           currency     TYPE waers,
           headertext   TYPE bktxt,
           referencedoc TYPE xblnr1,
           headerref1   TYPE zfi_de_xref1,
           to_item      TYPE TABLE OF ts_item WITH DEFAULT KEY,
         END OF ts_data.

  TYPES tt_data TYPE STANDARD TABLE OF ts_data WITH DEFAULT KEY.

  "============================================================
  " 3. KIỂU DỮ LIỆU HỖ TRỢ MAPPING (MAPPING HELPER TYPES)
  "============================================================
  TYPES: BEGIN OF ts_currency_amount_calc,
           currencyrole           TYPE c LENGTH 2,
           journalentryitemamount TYPE fins_vwcur12,
           currency               TYPE waers,
           exchangerate           TYPE zfi_de_kursf,
           taxbaseamount          TYPE fins_vwcur12,
         END OF ts_currency_amount_calc.

  TYPES tt_currency_amount_calc TYPE STANDARD TABLE OF ts_currency_amount_calc WITH DEFAULT KEY.

  TYPES: BEGIN OF ts_onetime_partner,
           name                        TYPE c LENGTH 40,
           onetimebusinesspartnername2 TYPE c LENGTH 40,
           onetimebusinesspartnername3 TYPE i_onetimeaccountsupplier-businesspartnername3,
           onetimebusinesspartnername4 TYPE i_onetimeaccountsupplier-businesspartnername4,
           cityname                    TYPE c LENGTH 40,
           country                     TYPE c LENGTH 3,
           vatliability                TYPE stceg,
           taxnumber1                  TYPE i_onetimeaccountsupplier-taxid1,
         END OF ts_onetime_partner.

  "============================================================
  " 4. KIỂU DỮ LIỆU TRẢ VỀ (RESPONSE / RESULT TYPES)
  "============================================================
  TYPES: BEGIN OF ts_result,
           filename           TYPE zfi_de_filename,
           id_doc             TYPE zfi_de_id_doc,
           type               TYPE string,
           message            TYPE string,
           accountingdocument TYPE string,
         END OF ts_result.

  TYPES tt_results TYPE STANDARD TABLE OF ts_result WITH DEFAULT KEY.

  TYPES: BEGIN OF ts_response,
           error   TYPE string,
           results TYPE STANDARD TABLE OF ts_result WITH EMPTY KEY,
         END OF ts_response.

  "============================================================
  " 5. KIỂU DỮ LIỆU THAM CHIẾU CHỨNG TỪ (DOCUMENT REFERENCE TYPE)
  "============================================================
  TYPES: BEGIN OF ts_accounting_document,
           accountingdocument TYPE belnr_d,
           companycode        TYPE bukrs,
           fiscalyear         TYPE gjahr,
         END OF ts_accounting_document.

  TYPES tt_post_data TYPE TABLE FOR ACTION IMPORT i_journalentrytp~post.

  "============================================================
  " 6. KIỂU DỮ LIỆU HỖ TRỢ SOAP (SOAP HELPER TYPES)
  "============================================================
  TYPES: BEGIN OF ts_soap_response,
           accountingdocument TYPE belnr_d,
           companycode        TYPE bukrs,
           fiscalyear         TYPE gjahr,
           has_error          TYPE abap_bool,
           messages           TYPE tt_results,
         END OF ts_soap_response.

ENDINTERFACE.
